[project]
name = "djangosnippets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "django==3.2",
    "django-bootstrap5>=24.1",
    "django-pygments-renderer>=0.0.1",
]
